-- MySQL Script generated by MySQL Workbench
-- Δευ 30 Ιαν 2023 04:37:19 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `address` VARCHAR(45) NULL,
  `connection_to_ai` LONGTEXT NULL,
  `summary` LONGTEXT NULL,
  `email` VARCHAR(45) NULL,
  `organisation_type` ENUM('Association', 'Centre', 'Company', 'Education Institution', 'Research Institution') NOT NULL,
  `relation_to_organisation` TINYINT(1) NOT NULL,
  `website` VARCHAR(45) NULL,
  `drupal_id` INT NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organisation_author_idx` (`author_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_organisation_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_asset` (
  `id` INT NOT NULL,
  `version` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `author_id` INT NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `asset_type` ENUM('As a Service', 'Dataset', 'Docker container', 'Executable', 'Jupyter Notebook', 'Library', 'ML Model', 'Tutorial') NOT NULL,
  `contact_details` LONGTEXT NULL DEFAULT NULL,
  `documentation` LONGTEXT NULL DEFAULT NULL,
  `organisation_id` INT NULL DEFAULT NULL,
  `gdpr_requirements` LONGTEXT NULL DEFAULT NULL,
  `image` LONGTEXT NULL DEFAULT NULL,
  `license` ENUM('2-clause BSD license (BSD-2-Clause)', '3-clause BSD license (BSD-3 Clause)', 'Apache License 2.0 (Apache-2.0)', 'Boost Software License 1.0', 'BSD+Patent (BSD-2-Clause-Patent)', 'Common Development and Distribution License 1.0 (CDDL-1.0)', 'Creative Commons Attribution 4.0 International License', 'Eclipse Public License 2.0 (EPL-2.0)', 'GNU General Public License (GP) v3 GNU Lesser General Public License (LGPL)', 'MIT license (MIT)', 'Mozilla Public License 2.0 (MPL-2.0)', 'Other') NULL DEFAULT NULL,
  `main_characteristic` LONGTEXT NOT NULL,
  `other_licence` LONGTEXT NULL DEFAULT NULL,
  `research_areas` ENUM('Collaborative AI', 'Explainable AI', 'Integrative AI', 'Physical AI', 'Verifiable AI') NULL DEFAULT NULL,
  `trustworthy_ai` LONGTEXT NULL DEFAULT NULL,
  `trustworthy_ai_assessment` ENUM('TRL 1-2 (Basic research)', 'TRL 3-5 (Technology development)', 'TRL 6-7 (Technology demonstration)', 'TRL 8-9 (System test & operation)') NULL DEFAULT NULL,
  `website` VARCHAR(45) NOT NULL,
  `under_review` TINYINT(1) NULL DEFAULT 0,
  `drupal_id` INT NOT NULL,
  PRIMARY KEY (`id`, `version`),
  INDEX `fk_ai_asset_author_idx` (`author_id` ASC),
  INDEX `fk_ai_asset_organisation_idx` (`organisation_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_ai_asset_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_asset_organisation`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `body` LONGTEXT NOT NULL,
  `media` ENUM('books', 'Eclipse', 'education', 'library') NULL DEFAULT NULL,
  `source` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_author_idx` (`author_id` ASC),
  CONSTRAINT `fk_news_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`open_call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`open_call` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `body` LONGTEXT NOT NULL,
  `media` ENUM('books', 'Eclipse', 'education', 'library') NULL DEFAULT NULL,
  `source` LONGTEXT NULL DEFAULT NULL,
  `drupal_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `finish_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_open_calls_author_idx` (`author_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_open_calls_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`case_study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`case_study` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `author_id` INT NOT NULL,
  `body` LONGTEXT NOT NULL,
  `organisation_id` INT NULL,
  `email` VARCHAR(45) NULL,
  `image` LONGTEXT NULL,
  `media` ENUM('books', 'Eclipse', 'education', 'library') NULL,
  `website` VARCHAR(45) NULL,
  `drupal_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_case_study_author_idx` (`author_id` ASC),
  INDEX `fk_case_study_organisation_idx` (`organisation_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_case_study_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_study_organisation`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `date_of_event` DATE NOT NULL,
  `description` LONGTEXT NOT NULL,
  `media` ENUM('books', 'Eclipse', 'education', 'library') NULL,
  `registration_link` VARCHAR(45) NULL,
  `revision_comments` LONGTEXT NULL,
  `event_type` ENUM('AI Event', 'Web Cafe') NULL,
  `drupal_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `finish_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_author_idx` (`author_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_event_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educational_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educational_resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NULL,
  `contact_details` LONGTEXT NULL,
  `country` VARCHAR(45) NULL,
  `credits` TINYINT(1) NULL,
  `duration_minutes_and_hours` ENUM('Less than 1 hour', '1-3 hours', '4-10 hours', '10+ hours') NULL,
  `organisation_id` INT NULL,
  `educational_type` ENUM('Distance Learning', 'Blended Learning', 'MOOC', 'On-site', 'Tutorial') NOT NULL,
  `educational_resourcecol` ENUM('1-3 hours (lower-paced)', '4-10 hours (quarter-speed)', '11-24 hours (Part-time)', '25-40 hours (intensive courses)') NULL,
  `tags` VARCHAR(45) NULL,
  `language` ENUM('International', 'Bulgarian', 'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Estonian', 'Finnish', 'French', 'German', 'Greek', 'Hungarian', 'Irish', 'Italian', 'Latvian', 'Lithuanian', 'Maltese', 'Polish', 'Portuguese', 'Romanian', 'Slovak', 'Slovenian', 'Spanish', 'Swedish') NOT NULL,
  `educational_level` ENUM('Basic', 'Advanced', 'Bachelor', 'Master') NOT NULL,
  `media` ENUM('books', 'Eclipse', 'education', 'library') NULL,
  `number_of_weeks` INT NULL,
  `pace` ENUM('Full-time', 'Part-time (scheduled)', 'Self-paced') NOT NULL,
  `prerequisites` VARCHAR(255) NULL,
  `body` LONGTEXT NOT NULL,
  `target_audience` SET('Working professionals', 'Students in Higher Education', 'Teachers in Secondary School') NOT NULL,
  `duration_years` INT NULL,
  `website` VARCHAR(45) NOT NULL,
  `drupal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_educational_resource_author_idx` (`author_id` ASC),
  INDEX `fk_educational_resource_organisation_idx` (`organisation_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_educational_resource_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educational_resource_organisation`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`business_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `published` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_UNIQUE` (`category` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`open_call_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`open_call_has_business_category` (
  `open_call_id` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`open_call_id`, `business_category_id`),
  INDEX `fk_business_category_has_open_calls_open_calls1_idx` (`open_call_id` ASC),
  INDEX `fk_business_category_has_open_calls_business_category1_idx` (`business_category_id` ASC),
  CONSTRAINT `fk_business_category_has_open_calls_business_category1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_business_category_has_open_calls_open_calls1`
    FOREIGN KEY (`open_call_id`)
    REFERENCES `mydb`.`open_call` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news_has_business_category` (
  `news_id` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`news_id`, `business_category_id`),
  INDEX `fk_business_category_has_news_news1_idx` (`news_id` ASC),
  INDEX `fk_business_category_has_news_business_category1_idx` (`business_category_id` ASC),
  CONSTRAINT `fk_business_category_has_news_business_category1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_business_category_has_news_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educational_resource_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educational_resource_has_business_category` (
  `educational_resource_id` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`educational_resource_id`, `business_category_id`),
  INDEX `fk_business_category_has_educational_resource_educational_r_idx` (`educational_resource_id` ASC),
  INDEX `fk_business_category_has_educational_resource_business_cate_idx` (`business_category_id` ASC),
  CONSTRAINT `fk_business_category_has_educational_resource_business_catego1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_business_category_has_educational_resource_educational_res1`
    FOREIGN KEY (`educational_resource_id`)
    REFERENCES `mydb`.`educational_resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`case_study_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`case_study_has_business_category` (
  `case_study_id` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`case_study_id`, `business_category_id`),
  INDEX `fk_case_study_has_business_category_business_category1_idx` (`business_category_id` ASC),
  INDEX `fk_case_study_has_business_category_case_study1_idx` (`case_study_id` ASC),
  CONSTRAINT `fk_case_study_has_business_category_case_study1`
    FOREIGN KEY (`case_study_id`)
    REFERENCES `mydb`.`case_study` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_case_study_has_business_category_business_category1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_has_business_category` (
  `event_id` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `business_category_id`),
  INDEX `fk_event_has_business_category_business_category1_idx` (`business_category_id` ASC),
  INDEX `fk_event_has_business_category_event1_idx` (`event_id` ASC),
  CONSTRAINT `fk_event_has_business_category_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_event_has_business_category_business_category1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`technical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`technical_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `published` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_UNIQUE` (`category` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`case_study_has_technical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`case_study_has_technical_category` (
  `case_study_id` INT NOT NULL,
  `technical_category_id` INT NOT NULL,
  PRIMARY KEY (`case_study_id`, `technical_category_id`),
  INDEX `fk_case_study_has_technical_category_technical_category1_idx` (`technical_category_id` ASC),
  INDEX `fk_case_study_has_technical_category_case_study1_idx` (`case_study_id` ASC),
  CONSTRAINT `fk_case_study_has_technical_category_case_study1`
    FOREIGN KEY (`case_study_id`)
    REFERENCES `mydb`.`case_study` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_case_study_has_technical_category_technical_category1`
    FOREIGN KEY (`technical_category_id`)
    REFERENCES `mydb`.`technical_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educational_resource_has_technical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educational_resource_has_technical_category` (
  `educational_resource_id` INT NOT NULL,
  `technical_category_id` INT NOT NULL,
  PRIMARY KEY (`educational_resource_id`, `technical_category_id`),
  INDEX `fk_educational_resource_has_technical_category_technical_ca_idx` (`technical_category_id` ASC),
  INDEX `fk_educational_resource_has_technical_category_educational__idx` (`educational_resource_id` ASC),
  CONSTRAINT `fk_educational_resource_has_technical_category_educational_re1`
    FOREIGN KEY (`educational_resource_id`)
    REFERENCES `mydb`.`educational_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_educational_resource_has_technical_category_technical_cate1`
    FOREIGN KEY (`technical_category_id`)
    REFERENCES `mydb`.`technical_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_has_technical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organisation_has_technical_category` (
  `organisation_id` INT NOT NULL,
  `technical_category_id` INT NOT NULL,
  PRIMARY KEY (`organisation_id`, `technical_category_id`),
  INDEX `fk_organisation_has_technical_category_technical_category1_idx` (`technical_category_id` ASC),
  INDEX `fk_organisation_has_technical_category_organisation1_idx` (`organisation_id` ASC),
  CONSTRAINT `fk_organisation_has_technical_category_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_organisation_has_technical_category_technical_category1`
    FOREIGN KEY (`technical_category_id`)
    REFERENCES `mydb`.`technical_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_asset_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_asset_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ai_asset_id` INT NOT NULL,
  `ai_asset_version` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `ai_asset_id`, `ai_asset_version`),
  INDEX `fk_ai_asset_review_ai_asset1_idx` (`ai_asset_id` ASC, `ai_asset_version` ASC),
  CONSTRAINT `fk_ai_asset_review_ai_asset1`
    FOREIGN KEY (`ai_asset_id` , `ai_asset_version`)
    REFERENCES `mydb`.`ai_asset` (`id` , `version`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organisation_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organisation_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `organisation_id`),
  INDEX `fk_organisation_review_organisation1_idx` (`organisation_id` ASC),
  CONSTRAINT `fk_organisation_review_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`open_call_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`open_call_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `open_call_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `open_call_id`),
  INDEX `fk_open_call_review_open_call1_idx` (`open_call_id` ASC),
  CONSTRAINT `fk_open_call_review_open_call1`
    FOREIGN KEY (`open_call_id`)
    REFERENCES `mydb`.`open_call` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `news_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `news_id`),
  INDEX `fk_news_review_news1_idx` (`news_id` ASC),
  CONSTRAINT `fk_news_review_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`news` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educational_resource_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educational_resource_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `educational_resource_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `educational_resource_id`),
  INDEX `fk_educational_resource_review_educational_resource1_idx` (`educational_resource_id` ASC),
  CONSTRAINT `fk_educational_resource_review_educational_resource1`
    FOREIGN KEY (`educational_resource_id`)
    REFERENCES `mydb`.`educational_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  `published` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`open_call_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`open_call_has_tag` (
  `open_call_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`open_call_id`, `tag_id`),
  INDEX `fk_open_call_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_open_call_has_tag_open_call1_idx` (`open_call_id` ASC),
  CONSTRAINT `fk_open_call_has_tag_open_call1`
    FOREIGN KEY (`open_call_id`)
    REFERENCES `mydb`.`open_call` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_open_call_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educational_resource_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educational_resource_has_tag` (
  `educational_resource_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`educational_resource_id`, `tag_id`),
  INDEX `fk_educational_resource_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_educational_resource_has_tag_educational_resource1_idx` (`educational_resource_id` ASC),
  CONSTRAINT `fk_educational_resource_has_tag_educational_resource1`
    FOREIGN KEY (`educational_resource_id`)
    REFERENCES `mydb`.`educational_resource` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_educational_resource_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news_has_tag` (
  `news_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`news_id`, `tag_id`),
  INDEX `fk_news_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_news_has_tag_news1_idx` (`news_id` ASC),
  CONSTRAINT `fk_news_has_tag_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`news` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_news_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `media` MEDIUMBLOB NULL,
  `funding_call` VARCHAR(45) NULL,
  `body` LONGTEXT NOT NULL,
  `image` LONGTEXT NULL,
  `acronym` LONGTEXT NULL,
  `project_type` SET('Micro-project in Humane-AI-Net', 'PhD project', 'Student project') NULL,
  `links` VARCHAR(45) NULL,
  `drupal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_author_idx` (`author_id` ASC),
  UNIQUE INDEX `drupal_id_UNIQUE` (`drupal_id` ASC),
  CONSTRAINT `fk_project_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `project_id`),
  INDEX `fk_project_review_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_review_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_ai_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_ai_asset` (
  `project_id` INT NOT NULL,
  `ai_asset_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `ai_asset_id`),
  INDEX `fk_project_has_ai_asset_ai_asset1_idx` (`ai_asset_id` ASC),
  INDEX `fk_project_has_ai_asset_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_ai_asset_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_ai_asset_ai_asset1`
    FOREIGN KEY (`ai_asset_id`)
    REFERENCES `mydb`.`ai_asset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_organisation` (
  `project_id` INT NOT NULL,
  `organisation_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `organisation_id`),
  INDEX `fk_project_has_organisation_organisation1_idx` (`organisation_id` ASC),
  INDEX `fk_project_has_organisation_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_organisation_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_project_has_organisation_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle` (
  `id` INT NOT NULL,
  `title` LONGTEXT NOT NULL,
  `author_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `additional_info` LONGTEXT NULL,
  `contact_details` LONGTEXT NOT NULL,
  `media` MEDIUMBLOB NULL,
  `image` LONGTEXT NULL,
  `project_type` SET('Micro-project in Humane-AI-Net', 'PhD project', 'Student project') NOT NULL,
  `links` VARCHAR(45) NULL,
  `body` LONGTEXT NOT NULL,
  `research_bundlecol` ENUM('TRL 1-2 (Basic research)', 'TRL 3-5 (Technology development)', 'TRL 6-7 (Technology demonstration)', 'TRL 8-9 (System test & operation)') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_research_bundle_author_idx` (`author_id` ASC),
  CONSTRAINT `fk_research_bundle_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_review` (
  `id` INT NOT NULL,
  `research_bundle_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `research_bundle_id`),
  INDEX `fk_research_bundle_review_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_review_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_tag` (
  `research_bundle_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `tag_id`),
  INDEX `fk_research_bundle_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_research_bundle_has_tag_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_tag_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_research_bundle_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_technical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_technical_category` (
  `research_bundle_id` INT NOT NULL,
  `technical_category_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `technical_category_id`),
  INDEX `fk_research_bundle_has_technical_category_technical_categor_idx` (`technical_category_id` ASC),
  INDEX `fk_research_bundle_has_technical_category_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_technical_category_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_research_bundle_has_technical_category_technical_category1`
    FOREIGN KEY (`technical_category_id`)
    REFERENCES `mydb`.`technical_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_ai_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_ai_asset` (
  `research_bundle_id` INT NOT NULL,
  `ai_asset_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `ai_asset_id`),
  INDEX `fk_research_bundle_has_ai_asset_ai_asset1_idx` (`ai_asset_id` ASC),
  INDEX `fk_research_bundle_has_ai_asset_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_ai_asset_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_ai_asset_ai_asset1`
    FOREIGN KEY (`ai_asset_id`)
    REFERENCES `mydb`.`ai_asset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_case_study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_case_study` (
  `project_id` INT NOT NULL,
  `case_study_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `case_study_id`),
  INDEX `fk_project_has_case_study_case_study1_idx` (`case_study_id` ASC),
  INDEX `fk_project_has_case_study_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_case_study_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_case_study_case_study1`
    FOREIGN KEY (`case_study_id`)
    REFERENCES `mydb`.`case_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_educational_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_educational_resource` (
  `project_id` INT NOT NULL,
  `educational_resource_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `educational_resource_id`),
  INDEX `fk_project_has_educational_resource_educational_resource1_idx` (`educational_resource_id` ASC),
  INDEX `fk_project_has_educational_resource_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_educational_resource_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_educational_resource_educational_resource1`
    FOREIGN KEY (`educational_resource_id`)
    REFERENCES `mydb`.`educational_resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_news` (
  `project_id` INT NOT NULL,
  `news_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `news_id`),
  INDEX `fk_project_has_news_news1_idx` (`news_id` ASC),
  INDEX `fk_project_has_news_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_news_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_news_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_event` (
  `project_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `event_id`),
  INDEX `fk_project_has_event_event1_idx` (`event_id` ASC),
  INDEX `fk_project_has_event_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_event_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_has_open_call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_has_open_call` (
  `project_id` INT NOT NULL,
  `open_call_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `open_call_id`),
  INDEX `fk_project_has_open_call_open_call1_idx` (`open_call_id` ASC),
  INDEX `fk_project_has_open_call_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_project_has_open_call_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_open_call_open_call1`
    FOREIGN KEY (`open_call_id`)
    REFERENCES `mydb`.`open_call` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_event` (
  `research_bundle_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `event_id`),
  INDEX `fk_research_bundle_has_event_event1_idx` (`event_id` ASC),
  INDEX `fk_research_bundle_has_event_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_event_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_case_study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_case_study` (
  `research_bundle_id` INT NOT NULL,
  `case_study_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `case_study_id`),
  INDEX `fk_research_bundle_has_case_study_case_study1_idx` (`case_study_id` ASC),
  INDEX `fk_research_bundle_has_case_study_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_case_study_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_case_study_case_study1`
    FOREIGN KEY (`case_study_id`)
    REFERENCES `mydb`.`case_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_educational_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_educational_resource` (
  `research_bundle_id` INT NOT NULL,
  `educational_resource_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `educational_resource_id`),
  INDEX `fk_research_bundle_has_educational_resource_educational_res_idx` (`educational_resource_id` ASC),
  INDEX `fk_research_bundle_has_educational_resource_research_bundle_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_educational_resource_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_educational_resource_educational_resou1`
    FOREIGN KEY (`educational_resource_id`)
    REFERENCES `mydb`.`educational_resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_open_call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_open_call` (
  `research_bundle_id` INT NOT NULL,
  `open_call_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `open_call_id`),
  INDEX `fk_research_bundle_has_open_call_open_call1_idx` (`open_call_id` ASC),
  INDEX `fk_research_bundle_has_open_call_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_open_call_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_open_call_open_call1`
    FOREIGN KEY (`open_call_id`)
    REFERENCES `mydb`.`open_call` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_news` (
  `research_bundle_id` INT NOT NULL,
  `news_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `news_id`),
  INDEX `fk_research_bundle_has_news_news1_idx` (`news_id` ASC),
  INDEX `fk_research_bundle_has_news_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_news_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_news_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`research_bundle_has_organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`research_bundle_has_organisation` (
  `research_bundle_id` INT NOT NULL,
  `organisation_id` INT NOT NULL,
  PRIMARY KEY (`research_bundle_id`, `organisation_id`),
  INDEX `fk_research_bundle_has_organisation_organisation1_idx` (`organisation_id` ASC),
  INDEX `fk_research_bundle_has_organisation_research_bundle1_idx` (`research_bundle_id` ASC),
  CONSTRAINT `fk_research_bundle_has_organisation_research_bundle1`
    FOREIGN KEY (`research_bundle_id`)
    REFERENCES `mydb`.`research_bundle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_research_bundle_has_organisation_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_asset_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_asset_has_business_category` (
  `ai_asset_id` INT NOT NULL,
  `ai_asset_version` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`ai_asset_id`, `ai_asset_version`, `business_category_id`),
  INDEX `fk_ai_asset_has_business_category_business_category1_idx` (`business_category_id` ASC),
  INDEX `fk_ai_asset_has_business_category_ai_asset1_idx` (`ai_asset_id` ASC, `ai_asset_version` ASC),
  CONSTRAINT `fk_ai_asset_has_business_category_ai_asset1`
    FOREIGN KEY (`ai_asset_id` , `ai_asset_version`)
    REFERENCES `mydb`.`ai_asset` (`id` , `version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_asset_has_business_category_business_category1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_asset_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_asset_has_tag` (
  `ai_asset_id` INT NOT NULL,
  `ai_asset_version` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`ai_asset_id`, `ai_asset_version`, `tag_id`),
  INDEX `fk_ai_asset_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_ai_asset_has_tag_ai_asset1_idx` (`ai_asset_id` ASC, `ai_asset_version` ASC),
  CONSTRAINT `fk_ai_asset_has_tag_ai_asset1`
    FOREIGN KEY (`ai_asset_id` , `ai_asset_version`)
    REFERENCES `mydb`.`ai_asset` (`id` , `version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_asset_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ai_asset_has_technical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ai_asset_has_technical_category` (
  `ai_asset_id` INT NOT NULL,
  `ai_asset_version` INT NOT NULL,
  `technical_category_id` INT NOT NULL,
  PRIMARY KEY (`ai_asset_id`, `ai_asset_version`, `technical_category_id`),
  INDEX `fk_ai_asset_has_technical_category_technical_category1_idx` (`technical_category_id` ASC),
  INDEX `fk_ai_asset_has_technical_category_ai_asset1_idx` (`ai_asset_id` ASC, `ai_asset_version` ASC),
  CONSTRAINT `fk_ai_asset_has_technical_category_ai_asset1`
    FOREIGN KEY (`ai_asset_id` , `ai_asset_version`)
    REFERENCES `mydb`.`ai_asset` (`id` , `version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ai_asset_has_technical_category_technical_category1`
    FOREIGN KEY (`technical_category_id`)
    REFERENCES `mydb`.`technical_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `category` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_category_1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_news_category_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`news_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`target_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`target_application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `application` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_target_application_1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_target_application_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`target_application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news_has_news_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news_has_news_category` (
  `news_id` INT NOT NULL,
  `news_category_id` INT NOT NULL,
  PRIMARY KEY (`news_id`, `news_category_id`),
  INDEX `fk_news_has_news_category_news_category1_idx` (`news_category_id` ASC),
  INDEX `fk_news_has_news_category_news1_idx` (`news_id` ASC),
  CONSTRAINT `fk_news_has_news_category_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_has_news_category_news_category1`
    FOREIGN KEY (`news_category_id`)
    REFERENCES `mydb`.`news_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`open_call_has_target_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`open_call_has_target_application` (
  `open_call_id` INT NOT NULL,
  `target_application_id` INT NOT NULL,
  PRIMARY KEY (`open_call_id`, `target_application_id`),
  INDEX `fk_open_call_has_target_application_target_application1_idx` (`target_application_id` ASC),
  INDEX `fk_open_call_has_target_application_open_call1_idx` (`open_call_id` ASC),
  CONSTRAINT `fk_open_call_has_target_application_open_call1`
    FOREIGN KEY (`open_call_id`)
    REFERENCES `mydb`.`open_call` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_open_call_has_target_application_target_application1`
    FOREIGN KEY (`target_application_id`)
    REFERENCES `mydb`.`target_application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`case_study_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`case_study_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `case_study_id` INT NOT NULL,
  `comment` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `case_study_id`),
  INDEX `fk_case_study_review_case_study1_idx` (`case_study_id` ASC),
  CONSTRAINT `fk_case_study_review_case_study1`
    FOREIGN KEY (`case_study_id`)
    REFERENCES `mydb`.`case_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organisation_has_business_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organisation_has_business_category` (
  `id` INT NULL,
  `organisation_id` INT NOT NULL,
  `business_category_id` INT NOT NULL,
  PRIMARY KEY (`organisation_id`, `business_category_id`),
  INDEX `fk_organisation_has_business_category_business_category1_idx` (`business_category_id` ASC),
  INDEX `fk_organisation_has_business_category_organisation1_idx` (`organisation_id` ASC),
  CONSTRAINT `fk_organisation_has_business_category_organisation1`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `mydb`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organisation_has_business_category_business_category1`
    FOREIGN KEY (`business_category_id`)
    REFERENCES `mydb`.`business_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
